apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guided-traffic-com.fullname" . }}-backend
  labels:
    {{- include "guided-traffic-com.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "guided-traffic-com.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guided-traffic-com.backendSelectorLabels" . | nindent 8 }}
        {{- with .Values.backend.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.extraPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.healthCheck.path }}
              port: {{ .Values.backend.healthCheck.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.backend.healthCheck.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
