apiVersion: v1
kind: Service
metadata:
  name: {{ include "guided-traffic-com.fullname" . }}-frontend
  labels:
    {{- include "guided-traffic-com.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "guided-traffic-com.frontendSelectorLabels" . | nindent 4 }}
